import "./globals.css";
import "@radix-ui/themes/styles.css"; // Глобальные стили
import { Theme } from "@radix-ui/themes";
import { Metadata } from "next";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Theme asChild appearance="dark" accentColor="tomato" grayColor="sand">
        <body>
          <Header />
          {children}
        </body>
      </Theme>
    </html>
  );
}
